preset: laravel

risky: false

enabled:
  - no_useless_else
  - phpdoc_align
  - phpdoc_order
  - phpdoc_separation
  - phpdoc_annotation_without_dot

finder:
  exclude:
    - "resources"
    - "storage"
    - "tests"
  not-path:
    - "bootstrap/cache"
